# Generated by Django 5.1.6 on 2025-02-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_created_at_post_last_modified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="posts.keyword"
            ),
        ),
    ]
