# Generated by Django 5.1.6 on 2025-02-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_blogimage_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
